DOCS.md

btw, the table of contents link to "--strict Mode" doesn't work (probably because of the leading dashes)

Fix multi-arg pipe backward docs

---

coconut/command.py
coconut/watch.py

Added file and directory watching flag. This is as requested in issue #99.
Usage:
```
coconut --watch examples/example.coco
coconut --watch examples
```
I did not use the watchdogs library because I wanted to keep dependencies minimal.

File watcher

---

setup.py

There's an extra pair of parentheses after `readlines`, so the installation fails.

Setup.py: Apparent typo fixed.

---

HELP.md

`plus1..square(3) == 10` currently returns False in the version on pip.

Add parens around function composition example.

---

HELP.md

imperative -> iterative.  The first example of `addpattern`, using `reduce`, is iterative rather than imperative.

Fix malapropism

---

DOCS.md

As per issue #315 I added a hint to the documentation.

Added documentation hint on parentheses around multi-line pipe operators

---

DOCS.md

Changed "pip install coocnut[...]" to "pip install coconut[...]"
I wasn't sure if opening a PR was the best way to suggest this fix, given how minor it is, so feel free to close the PR if it was not.

Fixing typo in the "Optional Dependencies" section

---

coconut/compiler/util.py
tests/src/cocotest/agnostic/suite.coco

Try to match the might-be-parenthesised item first before trying to
match the parenthesised form.  This allows the first element within the
item to also be parenthesised.
Fixes: #359

Fix parser maybeparens

---

.gitignore
MANIFEST.in
Makefile
coconut/compiler/compiler.py
coconut/compiler/grammar.py
coconut/compiler/matching.py
coconut/compiler/util.py
coconut/constants.py
coconut/exceptions.py
coconut/pyparsing.py
coconut/terminal.py

Instead of greedily applying parse actions, build a computation graph that only gets executed after everything has been parsed. Implements #299.

Use a computation graph

---

coconut/command/util.py

While trying to make coconut run on prompt_toolkit 2.0, I discovered that this Pygments import was missing.
```python
Traceback (most recent call last):
File "/home/jonathan/git/coconut/coconut/command/command.py", line 270, in handling_exceptions
yield
File "/home/jonathan/git/coconut/coconut/command/command.py", line 118, in cmd
self.use_args(parsed_args, interact, original_args=args)
File "/home/jonathan/git/coconut/coconut/command/command.py", line 156, in use_args
self.prompt.set_style(args.style)
File "/home/jonathan/git/coconut/coconut/command/util.py", line 332, in set_style
elif style in pygments.styles.get_all_styles():
AttributeError: module 'pygments' has no attribute 'styles'
```
Maybe this wasn't required in prompt_toolkit 1.0 because prompt_toolkit did this import for you. …

Added missing pygments.styles import.

---

HELP.md

Add more examples to section on function composition for #437. The examples use the updated behavior of the `..` operator.

Improve documentation on function composition

---

DOCS.md

This PR addresses issue #445, adding information that was previously missing around how Coconut handles indexing into iterables.

Improve documentation on iterable indexing

---

DOCS.md

This commit fixes the docs for issue #404.

Remove reference to --mypy flag disabling tail call optimization

---

DOCS.md

This PR improves the docs on the None-coalescing operator `??` and its brethren (`?.`, `?[]`, `??=`, etc.), addressing issue #420. The documentation now links to [PEP 505](https://www.python.org/dev/peps/pep-0505/) as well.

Improved documentation on None-aware operators

---

DOCS.md

Expands the documentation on tail call optimization and tail recursion elimination, particularly relating to the `--no-tco` flag. This is intended to cover issue #363.

Expand documentation on TCO/TRE

---

DOCS.md

This PR clarifies the enhanced type annotation syntax for sequences/lists, as discussed in issue #353.

Improve enhanced type annotation docs on sequences

---

coconut/compiler/compiler.py
tests/src/cocotest/agnostic/main.coco

The added implementation XORs the `tuple.__hash__` of the data object with the hash of the class.  This should help to avoid collisions between instances of different data types with identical members.
Also added a test which ensures that:
* hash of a data type instance can be computed;
* hashes of instances of different data types with same data differ;
* hash of a data type instance differs from hash of a plain tuple.
Fixes #446.

Add __hash__ on data types

---

coconut/compiler/compiler.py
coconut/compiler/header.py
coconut/compiler/matching.py
coconut/compiler/templates/header.py_template
coconut/constants.py
coconut/root.py
coconut/stubs/__coconut__.pyi
tests/src/cocotest/agnostic/suite.coco

This change introduces a context stack with MatchError subclasses that pattern-matching functions must raise instead of plain MatchError.
This works the following way:
* Every time a function is decorated with @addpattern, a subclass of MatchError is created and stored in the local scope;
* when such function is called, this subclass is put on the stack before execution of addpattern's base_func;
* when a pattern-matching function is called, it checks whether the exception class at the top of the stack has been already taken;
* if it wasn't, the function marks it as taken (so that no other function would take it from the stack) and will raise it instead of plain MatchError;
* inside addpattern, this specific exception is caught instead of MatchError.
As a result, any pattern-matching …

Fix addpattern incorrectly catching all MatchErrors

---

coconut/compiler/templates/header.py_template
tests/src/cocotest/agnostic/main.coco

Hello, I found what I think is a bug and it's solution. Consider the following 
```
a = [2] :: [2]
a = a |> reiterable
b = a |> reiterable
b |> list |> print
b |> list |> print
a |> list |> print
a |> list |> print
```
Since both `a` and `b` are reiterable, I expect the output to be 
```
[2, 2]
[2, 2]
[2, 2]
[2, 2]
```
However the actual output is 
```
[2, 2]
[]
[]
[]
```
This is caused by the call to copy in the `__copy__` method in reiterable, which depletes the iterator. Instead of this I think tee should be used here to copy the iterator when making a new copy. The commit makes this change, which causes the above example to act as expected. I can add the above example as a test if you'd like

Change reiterable __copy__ method to use tee instead of copy, as copy depletes the iterator

---

DOCS.md

This change adds the documentation requested in #481; it adds info on using type annotations with statement lambdas and notes that users should use statement lambdas if they want to use type annotations on the parameters to their lambda.

Docs on type annotations for the parameters of statement lambdas

---

DOCS.md

This makes the change to the documentation discussed in issue #479, adding more information on implicit lambdas and adding a warning about nesting multiple implicit lambdas.

Add warning about nesting implicit lambdas to documentation

---

CONTRIBUTING.md
coconut/compiler/compiler.py
coconut/compiler/util.py
tests/main_test.py
tests/src/cocotest/agnostic/main.coco
tests/src/cocotest/target_36/py36_test.coco

This allows writing code like `f"{[] |> len}"`.
Fixes #504.

Parse f-string expressions as Coconut

---

coconut/command/cli.py
coconut/command/command.py
coconut/compiler/compiler.py

This adds a `no-wrap` flag to the compiler to disable wrapping typedefs to resolve #514 
I'm a bit mixed about the name of the flag, I feel like it's too ambiguous and I'm very much open to changing it.

Add no-wrap Flag for optional typedef wrapping

---

DOCS.md
coconut/compiler/util.py

There is a small typo in DOCS.md, coconut/compiler/util.py.
Should read `separated` rather than `seperated`.

docs: Fix simple typo, seperated -> separated

---

coconut/requirements.py

On some build systems (such as `nix-unstable`) there is a 4th non-numeric patch
version such as `47.3.1.post20201006` that causes this version extraction to
fail. Since the code only requires the numeric part the extraction is limited to
the `major.minor` part of `major.minor.patch.patch-date`.

[fix] Error on non-numeric patch version

---

coconut/command/cli.py
coconut/command/command.py
tests/main_test.py

This add the option to include `--and additional/src additional/dest` to the CLI arguments.  It works under the assumption that other flags that are passed should apply to all source/dest pairs.
In addition to the automated test, I did some manual testing.  It confirmed that compiling multiples of the same file to different destinations, and multiples of different files to the same destination worked as expected. This was both with overlapping and non-overlapping names. This was tested with up to 2 `--and` pairs.

Issue #587  Add --and for doing extra compilation with the same arguments

---

DOCS.md

The example as written for the pure-Python equivalent of scan() acts as a pass-through operator; this is due to a typo in the code, where `x` is appended to the output instead of `max_so_far`, as the actual behaviour of `scan` would require

Fix typo in pure-Python example for scan()

---

DOCS.md

Changed pipe function applications to valid regular Python function calls in the flatten pure-Python example.

Fixed pure-Python example in flatten docs

---

.pre-commit-config.yaml
DOCS.md
Makefile
__coconut__/__init__.pyi
coconut/_pyparsing.py
coconut/command/util.py
coconut/compiler/compiler.py
coconut/compiler/grammar.py
coconut/compiler/header.py
coconut/compiler/matching.py
coconut/compiler/templates/header.py_template
coconut/compiler/util.py
coconut/constants.py
coconut/icoconut/root.py
coconut/requirements.py
coconut/root.py
coconut/tests/main_test.py
coconut/tests/src/cocotest/agnostic/main.coco
coconut/tests/src/cocotest/agnostic/primary_1.coco
coconut/tests/src/cocotest/agnostic/primary_2.coco
coconut/tests/src/cocotest/agnostic/suite.coco
coconut/tests/src/cocotest/agnostic/tutorial.coco
coconut/tests/src/cocotest/target_2/py2_test.coco
coconut/tests/src/extras.coco

See Coconut's [documentation](http://coconut.readthedocs.io/en/develop/DOCS.html) for more information on all of the features listed below.
Bugfixes:
* #851, #852: Fixed comments inside of parentheses in the Jupyter kernel.
Language features:
* #846: `reduce`, `takewhile`, and `dropwhile` now support keyword arguments.
* #848: Class and data patterns now support keyword argument name elision.
* #847: New pattern-matching syntax for matching anonymous named tuples.
Compiler features:
* #843: Added compiler warnings for (some cases of) undefined variables.

Release v3.1.2
